### ISSUE TITLE
tips

### ISSUE THREAD

**Issue by Boos4721** [Win10Q/hackintosh-6700k-hd530-z170#1]
GJ! add `AirportItlwm.kext` for wireless

**Comment by Boos4721** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/43845654/177505719-bde37e0a-d3de-4d5f-a4e7-e64d3849eded.png">

**Comment by Win10Q** [comment]
thanks for you！

**Comment by Boos4721** [comment]
> thanks for you！

cheers！

**Comment by Win10Q** [comment]
I will add it

**Comment by Boos4721** [comment]
> I will add it

kk, btw we can talk as Chinese.

**Comment by Win10Q** [comment]
你好

**Comment by Win10Q** [comment]
我认为还需要添加intel蓝牙驱动

**Comment by Boos4721** [comment]
> 我认为还需要添加intel蓝牙驱动

是的 只需要写一下内核版本限制

**Comment by Win10Q** [comment]
确实

**Comment by Win10Q** [comment]
我加了12wifi

**Comment by Boos4721** [comment]
> 我加了12wifi

可以 bios的设置也可以加入到readme中

**Comment by Win10Q** [comment]
我懒得写了，bios可以看11400的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月6日(星期三) 下午4:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Win10Q/hackintosh-6700k-hd530-z170] tips (Issue #1)





  
我加了12wifi
  
可以 bios的设置也可以加入到readme中

**Comment by Win10Q** [comment]
加了，在re发布了

**Comment by Boos4721** [comment]
> 我懒得写了，bios可以看11400的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月6日(星期三) 下午4:47 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Win10Q/hackintosh-6700k-hd530-z170] tips (Issue #1) 我加了12wifi 可以 bios的设置也可以加入到readme中 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Ok 等下我给你个pr

**Comment by Boos4721** [comment]
我手上有张r7 240不知道能不能用

**Comment by Boos4721** [comment]
不知道为啥我用不了。。 直接到EB就重启了

**Comment by Boos4721** [comment]
难道是bios还要设置其他的么

**Comment by Boos4721** [comment]
https://www.drixn.com/21.html 对着这个改的
